version: '3.4'

services:
  db:
    build: ./postgis
    restart: always
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7.1
    restart: always
    ports:
      - 8010:8080
    depends_on: 
      - db

  geo:
    build: ./geoserver
    restart: always
    ports:
      - 8011:8080
    depends_on: 
      - db
